from app.core.database import SessionLocal
from app.models import ADRRecord
from datetime import datetime
import json


def generate_ticket(adr_id: str, platform: str = "github") -> dict:
    db = SessionLocal()
    try:
        adr = db.query(ADRRecord).filter(ADRRecord.id == adr_id).first()
        if not adr:
            return {"error": "ADR not found"}

        severity_history = _get_adr_severity_history(adr_id)

        if platform == "github":
            ticket = _build_github_issue(adr, severity_history)
        else:
            ticket = _build_generic_ticket(adr, severity_history)

        return ticket
    finally:
        db.close()


def _get_adr_severity_history(adr_id: str) -> list[dict]:
    return []


def _build_github_issue(adr: ADRRecord, severity_history: list[dict]) -> dict:
    title = f"[ADR-{str(adr.id)[:8]}] {adr.title}"

    body_parts = [
        f"## Architectural Decision Record",
        f"**ADR ID:** `{adr.id}`",
        f"**Status:** {adr.status}",
        f"**Approved by:** {adr.approved_by or 'Pending'}",
        f"**Created:** {adr.created_at.isoformat() if adr.created_at else 'N/A'}",
        "",
        "### Context",
        adr.context or "No context provided.",
        "",
        "### Decision",
        adr.decision or "No decision documented.",
        "",
        "### Consequences",
        adr.consequences or "No consequences documented.",
        "",
        "---",
        "### Cognitive Trace",
        f"- [View in Decision Lineage](/)",
        f"- [Governance Timeline](/)",
        f"- ADR predecessor: `{adr.predecessor_id or 'None'}`",
        "",
        "### Implementation Checklist",
        "- [ ] Review ADR context and decision",
        "- [ ] Implement changes per architectural decision",
        "- [ ] Verify no forbidden synonyms in codebase",
        "- [ ] Update governance documentation if needed",
        "- [ ] Request architecture review before merge",
        "",
        "---",
        f"*Generated by Cognitive SDLC Workspace on {datetime.utcnow().isoformat()}*",
    ]

    body = "\n".join(body_parts)

    labels = ["architecture", "governance"]
    if adr.status == "Approved":
        labels.append("approved")
    elif adr.status == "Deprecated":
        labels.append("deprecated")

    return {
        "platform": "github",
        "title": title,
        "body": body,
        "labels": labels,
        "adr_id": str(adr.id),
        "created_at": datetime.utcnow().isoformat(),
    }


def _build_generic_ticket(adr: ADRRecord, severity_history: list[dict]) -> dict:
    return {
        "platform": "generic",
        "title": adr.title,
        "description": adr.context,
        "adr_id": str(adr.id),
        "status": adr.status,
        "created_at": datetime.utcnow().isoformat(),
    }
